### ISSUE TITLE
Mod seams to make server console not display correctly

### ISSUE THREAD

**Issue by PixelatedBruh** [P3NG00/MoreCraftingTables#1]
Without
![test](https://user-images.githubusercontent.com/54760551/89542280-4fbb9500-d7b4-11ea-9fda-1a6ab5fff551.PNG)
With
![test1](https://user-images.githubusercontent.com/54760551/89542290-52b68580-d7b4-11ea-94a1-88fa714379bd.PNG)

It is making my fabric-discord bot kind of useless. It also does it for other things such as normal chat. It ends up as something like client.chat.menu or something similar.

**Comment by Nathan22211** [comment]
I doubt this mod touches that, did you try it with just this mod and Fabric API

**Comment by LazyShpee** [comment]
@Nathan22211 Yes it does, as stated in the [fabric lang tutorial](https://fabricmc.net/wiki/tutorial:lang), the path for the translation strings file should look something like this `resources/assets/ohtcht/lang/en_us.json` whereas here @P3NG00 has put it in `resources/assets/minecraft/lang/en_us.json`, replacing the original lang file.

In hindsight, the reason they did this was to rename the original crafting table to "Oak Crafting Table". The solution remains roughly the same, just deleting [`resources/assets/minecraft/lang/en_us.json`](https://github.com/P3NG00/OhHowTheCraftingHasTabled/blob/master/src/main/resources/assets/minecraft/lang/en_us.json) and placing the translation string in [`resources/assets/morecraftingtables/lang/en_us.json`](https://github.com/P3NG00/OhHowTheCraftingHasTabled/blob/master/src/main/resources/assets/morecraftingtables/lang/en_us.json) works.

**Comment by P3NG00** [comment]
Will look into this tonight

**Comment by P3NG00** [comment]
> In hindsight, the reason they did this was to rename the original crafting table to "Oak Crafting Table". The solution remains roughly the same, just deleting [`resources/assets/minecraft/lang/en_us.json`](https://github.com/P3NG00/OhHowTheCraftingHasTabled/blob/master/src/main/resources/assets/minecraft/lang/en_us.json) and placing the translation string in [`resources/assets/morecraftingtables/lang/en_us.json`](https://github.com/P3NG00/OhHowTheCraftingHasTabled/blob/master/src/main/resources/assets/morecraftingtables/lang/en_us.json) works.

@LazyShpee I have 2 'en_us.json' files: one under "minecraft" and one under "morecraftingtables" (the modid).

@PixelatedBruh what discord bot are you using?

**Comment by P3NG00** [comment]
@PixelatedBruh

Just bumping my last comment. I won't be able to help if I don't understand the problem. If you tell me what you're using as a Discord bot maybe I can get some more information

**Comment by P3NG00** [comment]
@LazyShpee I don't think I read your comment correctly last time. I've implemented this fix in upcoming 0.1.2
